server:
  port: 9091

spring:
  application:
    name: res-product-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant_product_service
    username: postgres
    password: adgjmp123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master-changelog.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
